build:
  image: php:$$PHP_VERSION
  commands:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-interaction --no-progress
    - ./vendor/bin/phpunit
  environment:


compose:
  redis:
    image: redis:latest

matrix:
  PHP_VERSION:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
