nginx:
  build: nginx
  links:
    - drone
  ports:
    - "80:80"

db:
  image: postgres
  expose:
    - "5432"

drone:
  build: .
  links:
    - db
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./data/lib/:/var/lib/drone"
  environment:
      DRONE_SERVER_PORT: "0.0.0.0:8080"
      DRONE_GITHUB_CLIENT: ""
      DRONE_GITHUB_SECRET: ""
  expose:
    - "8080"
